import type { InvoiceDocument } from "./types";

export function toDbRow(doc: InvoiceDocument, userId: string) {
  return {
    user_id: userId,
    type: doc.type,
    number: doc.number,
    currency: doc.currency,
    theme: doc.theme,
    status: doc.status,
    from_text: doc.from_text,
    to_text: doc.to_text,
    ship_to_text: doc.ship_to_text,
    date: doc.date,
    due_date: doc.due_date,
    payment_terms: doc.payment_terms,
    po_number: doc.po_number,
    labels: doc.labels,
    items: doc.items,
    tax_mode: doc.tax_mode,
    tax_value: doc.tax_value,
    discount_mode: doc.discount_mode,
    discount_value: doc.discount_value,
    shipping_mode: doc.shipping_mode,
    shipping_value: doc.shipping_value,
    amount_paid: doc.amount_paid,
    notes: doc.notes,
    terms: doc.terms,
    logo_url: doc.logo_url,
    updated_at: new Date().toISOString(),
    sent_at: doc.sent_at ?? null,
  };
}

export function fromDbRow(row: Record<string, unknown>): InvoiceDocument {
  return {
    id: String(row.id),
    user_id: (row.user_id as string) ?? null,
    type: row.type as InvoiceDocument["type"],
    number: String(row.number ?? "1"),
    currency: String(row.currency ?? "USD"),
    theme: (row.theme as InvoiceDocument["theme"]) ?? "classic",
    status: (row.status as InvoiceDocument["status"]) ?? "draft",
    from_text: String(row.from_text ?? ""),
    to_text: String(row.to_text ?? ""),
    ship_to_text: String(row.ship_to_text ?? ""),
    date: String(row.date ?? ""),
    due_date: String(row.due_date ?? ""),
    payment_terms: String(row.payment_terms ?? ""),
    po_number: String(row.po_number ?? ""),
    labels: row.labels as InvoiceDocument["labels"],
    items: (row.items as InvoiceDocument["items"]) ?? [],
    tax_mode: (row.tax_mode as InvoiceDocument["tax_mode"]) ?? "percent",
    tax_value: Number(row.tax_value ?? 0),
    discount_mode: (row.discount_mode as InvoiceDocument["discount_mode"]) ?? "off",
    discount_value: Number(row.discount_value ?? 0),
    shipping_mode: (row.shipping_mode as InvoiceDocument["shipping_mode"]) ?? "off",
    shipping_value: Number(row.shipping_value ?? 0),
    amount_paid: Number(row.amount_paid ?? 0),
    notes: String(row.notes ?? ""),
    terms: String(row.terms ?? ""),
    logo_url: (row.logo_url as string) ?? null,
    created_at: row.created_at as string | undefined,
    updated_at: row.updated_at as string | undefined,
    sent_at: (row.sent_at as string) ?? null,
  };
}
